spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: 7561
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
security:
  secret: n123aa4d89abcdef01c3bb6789abcdefxyz9876543210abcdeffedcba987654321
  expireTimeMs: 120000